apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
    tier: api

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        tier: api

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: backend

          image: 730024653391.dkr.ecr.ap-south-1.amazonaws.com/backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8086

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # App takes ~62s to start, so total window = 30 + (15×10) = 180s
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 15

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3